map:
  width: 10
  heigth: 10

entity_count:
  HERBIVORE: 4
  ROCK: 12
  TREE: 12
  GRASS: 10
  PREDATOR: 3

entity_char:
  herbivore_hp: 3
  predator_hp: 3
  herbivore_speed: 2
  predator_speed: 1
  power_attack_predator: 1